### PR TITLE
Fix milliseconds rounding inconsistency

### LINKED ISSUE #38: Rounding inconsistency
When formatting 11999 milliseconds using default options, the result is `1m 60s` (should obviously be `2m`). Looking at the unit tests I also didn't quite understand why seconds round down

```js
	t.is(prettyMilliseconds(33333, {secondsDecimalDigits: 0}), '33s');
```

but milliseconds round up:

```js
	t.is(prettyMilliseconds(33.333, {millisecondsDecimalDigits: 0}), '34ms');
```

Is there some reason why seconds round as we expect them to (mathematically), but milliseconds seem to round up?

### PR DESCRIPTION
**Pull request by explodingcamera**
While everything below `0.1ms` keeps the old behavior and gets rounded up to `1ms`, everything over that uses `Math.round`.
Also fixes the issue with 11999 milliseconds rounding to `1m 60s`.
Fixes #38

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -37,6 +37,17 @@ module.exports = (milliseconds, options = {}) => {
 		}
 	}
 
+	if (
```
Comment (sindresorhus) [inline index.js]: Would be good to add a comment about what's happening here.

File: index.js [hunk 2]
```diff
@@ -37,6 +37,17 @@ module.exports = (milliseconds, options = {}) => {
...
+		milliseconds >= (1000 * 60) - 50 &&
```
Comment (sindresorhus) [inline index.js]: `50` should be a constant because it's not clear what it's for.

**Comment by villebro** [comment]
@explodingcamera are you planning on implementing the requested changes? If not, I don't mind implementing the fix.

File: index.js (hunk 2 above)
Comment (explodingcamera) [reply index.js]: Should be clear now
